version: '3.3'
services:
  # backend:
  #   build: ./backend
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - .env
  #   ports:
  #     - '5000:5000'
  #   restart: on-failure
  #   depends_on:
  #     - nginx
  #   networks:
  #     - app-network
  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/etc/ssl/:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
