version: '3.3'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.local
    environment:
      NEXT_PUBLIC_APP_NODE_ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/etc/ssl/:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
